-- ============================================================================
-- schema-version-table.sql
-- In-house migration-history mechanism, for environments where Flyway or
-- Liquibase (the standard industry tools for this -- prefer adopting one of
-- those over this template if the project's tooling allows it) aren't
-- available. Modeled on the same information Flyway's own history table
-- tracks: an ordered version, a description, the script that ran, a
-- checksum, who/when applied it, and whether it succeeded.
--
-- `APP_` is a PLACEHOLDER prefix -- substitute your project's actual
-- registered prefix.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. THE VERSION/CHANGELOG TABLE ITSELF -- create once, per schema.
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'APP_SCHEMA_VERSION_T';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         CREATE TABLE app_schema_version_t (
            version_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            version_label            VARCHAR2(50 CHAR)  NOT NULL,   -- e.g. ''2026.07.30.01'', monotonic and sortable
            description              VARCHAR2(400 CHAR) NOT NULL,
            script_name              VARCHAR2(200 CHAR) NOT NULL,   -- forward script filename
            rollback_script_name     VARCHAR2(200 CHAR),            -- paired rollback script filename, NULL only for
                                                                       -- an Additive change class that genuinely has none
                                                                       -- (schema-promote''s rollback-policy table) --
                                                                       -- not simply "didn''t get around to writing one"
            change_class             VARCHAR2(20 CHAR)  NOT NULL,   -- ADDITIVE / DROP / BACKFILL / PACKAGE
            checksum                 VARCHAR2(64 CHAR)  NOT NULL,   -- hash of the applied script -- detects an edit to
                                                                       -- an already-applied migration (immutability rule)
            applied_by               VARCHAR2(128 CHAR) NOT NULL,
            applied_date             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            status                   VARCHAR2(10 CHAR)  NOT NULL,   -- SUCCESS / FAILED
            CONSTRAINT app_schema_version_pk PRIMARY KEY (version_id),
            CONSTRAINT app_schema_version_uk1 UNIQUE (version_label),
            CONSTRAINT app_schema_version_ck1 CHECK (change_class IN (''ADDITIVE'',''DROP'',''BACKFILL'',''PACKAGE'')),
            CONSTRAINT app_schema_version_ck2 CHECK (status IN (''SUCCESS'',''FAILED''))
         )';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 2. THE IMMUTABILITY RULE -- once a row is recorded here, it does not get
--    UPDATEd to change what happened; a correction is a NEW row (a later
--    version) that fixes the mistake, same as Flyway/Liquibase enforce via
--    checksum validation against re-running an edited migration. This trigger
--    is the in-house equivalent of that enforcement: it blocks UPDATE/DELETE
--    on any row already marked SUCCESS, so history can't be silently
--    rewritten -- if a status genuinely needs correcting (e.g. FAILED ->
--    investigate -> actually SUCCESS after a manual fix), that's a deliberate,
--    logged DBA action outside the app path, not routine.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER app_schema_version_immut_trg
BEFORE UPDATE OR DELETE ON app_schema_version_t
FOR EACH ROW
BEGIN
   IF :OLD.status = 'SUCCESS' THEN
      RAISE_APPLICATION_ERROR(-20951,
         'app_schema_version_t is append-only for SUCCESS rows -- version '
         || :OLD.version_label || ' cannot be modified or deleted. '
         || 'Record a new migration instead of editing history.');
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 3. WORKED EXAMPLE -- recording a forward migration + its rollback pairing
--    after applying schema-emit's business-table.sql to create APP_ORDER_T.
--    Compute the checksum however the project's tooling does (a SHA-256 of
--    the script file's bytes is typical; ASSUMPTION: the exact hash function
--    is a project choice, not fixed by this template -- DBMS_CRYPTO.HASH is
--    one way to compute it from within the database itself if the script
--    text is staged as a CLOB before this INSERT runs).
-- ----------------------------------------------------------------------------
-- INSERT INTO app_schema_version_t
--    (version_label, description, script_name, rollback_script_name,
--     change_class, checksum, applied_by, status)
-- VALUES
--    ('2026.07.30.01', 'Add APP_ORDER_T business table',
--     'business-table.sql', NULL, 'ADDITIVE',
--     'a3f5e1...(sha-256 of the applied script)', USER, 'SUCCESS');
-- COMMIT;

-- ----------------------------------------------------------------------------
-- 4. NAMING CONVENTION FOR THE FORWARD/ROLLBACK SCRIPT PAIR -- pick one and
--    hold it. A common, Flyway-compatible shape:
--       V2026.07.30.01__add_app_order_t.sql      (forward)
--       U2026.07.30.01__add_app_order_t.sql      (rollback / "undo",
--                                                  Flyway's own convention for
--                                                  the optional undo variant)
--    The version label in the filename should match version_label above
--    exactly, so the pairing is mechanically verifiable, not just readable.
-- ----------------------------------------------------------------------------
