-- ============================================================================
-- schema-emit :: business-table.sql
-- Illustrative worked example: APP_ORDER_T -- a customer's order. Business
-- table shape per schema-model step 2: has its own row identity + lifecycle,
-- referenced by other tables (e.g. a line-item table would FK to this one),
-- carries more than a code+meaning pair.
--
-- `APP_` is a PLACEHOLDER prefix -- substitute your project's actual
-- registered table-name prefix and the case convention schema-model.md §0
-- settled on for this session. Every identifier below is find-and-replace,
-- not a name to ship literally.
--
-- Audit ("WHO") column types/widths and the CHAR(1)-vs-BOOLEAN choice follow
-- schema-model.md §4/§6. Two PK-population strategies are shown per
-- schema-model.md §7 -- IDENTITY (recommended, active below) and
-- SEQUENCE + TRIGGER (adopt-in-place path, commented) -- pick ONE per table,
-- never both driving the same column.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABLE -- idempotent via a data-dictionary existence check (schema-emit's
--    SKILL.md "Idempotency" section) rather than a catch-and-swallow block --
--    the guard below can only be a real no-op, never an accidental mask of an
--    unrelated failure, because the CREATE is never attempted once the
--    dictionary already shows the table.
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'APP_ORDER_T';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         CREATE TABLE app_order_t (
            -- PK strategy A (recommended, greenfield): identity column.
            -- GENERATED BY DEFAULT ON NULL, not GENERATED ALWAYS -- ALWAYS
            -- rejects any INSERT that supplies an explicit value (breaks a
            -- cross-schema copy/migration script); BY DEFAULT ON NULL still
            -- auto-generates on NULL/omitted, but accepts an explicit value
            -- when one is supplied.
            order_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            -- PK strategy B (adopt-in-place path -- use this OR strategy A,
            -- never both): plain NUMBER, populated by a BEFORE INSERT trigger
            -- from a sequence (see section 4 below).
            -- order_id              NUMBER            NOT NULL,

            customer_id              NUMBER            NOT NULL,
            order_number             VARCHAR2(30 CHAR) NOT NULL,
            order_status_code        VARCHAR2(15 CHAR) NOT NULL,
            order_total              NUMBER(12,2)      DEFAULT 0 NOT NULL,

            -- boolean-shaped column, CHAR(1) form (schema-model.md §6,
            -- portable choice / correct on pre-23ai):
            backorder_allowed_flag   CHAR(1)           DEFAULT ''N'' NOT NULL,
            -- 23ai-native alternative (greenfield 23ai+ only -- NOTE: BOOLEAN
            -- columns cannot be indexed, so prefer CHAR(1) if this column
            -- will ever need an index as a filter/join predicate):
            -- backorder_allowed     BOOLEAN           DEFAULT FALSE NOT NULL,

            active_flag              CHAR(1)                  DEFAULT ''Y'' NOT NULL,

            -- Audit ("WHO") columns -- TIMESTAMP WITH TIME ZONE is the
            -- recommended default (schema-model.md §4); use plain
            -- DATE/SYSDATE only as a legacy-compatibility match to an
            -- existing schema that already uses DATE throughout.
            created_by               VARCHAR2(128 CHAR)       NOT NULL,
            creation_date            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            last_updated_by          VARCHAR2(128 CHAR)       NOT NULL,
            last_update_date         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            object_version_number    NUMBER                   DEFAULT 1 NOT NULL,

            CONSTRAINT app_order_pk PRIMARY KEY (order_id),
            CONSTRAINT app_order_uk1 UNIQUE (order_number),
            CONSTRAINT app_order_ck1 CHECK (active_flag IN (''Y'',''N'')),
            CONSTRAINT app_order_ck2 CHECK (backorder_allowed_flag IN (''Y'',''N''))
         )';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 2. FK CONSTRAINT -- customer_id -> APP_CUSTOMER_T, RESTRICT (Oracle's
--    default: no ON DELETE clause) per schema-model.md step 3 -- a customer
--    is a shared master entity and must not silently vanish out from under a
--    live order.
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count
     FROM user_constraints
    WHERE table_name = 'APP_ORDER_T' AND constraint_name = 'APP_ORDER_FK1';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         ALTER TABLE app_order_t
            ADD CONSTRAINT app_order_fk1
            FOREIGN KEY (customer_id) REFERENCES app_customer_t (customer_id)';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 3. FK INDEX -- mandatory (schema-model.md §8: Oracle never
--    auto-indexes an FK column). customer_id is not the leading column of any
--    existing UNIQUE/PK index on this table, so this index is required, not
--    optional.
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'APP_ORDER_IDX1';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         CREATE INDEX app_order_idx1 ON app_order_t (customer_id)';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 4. SEQUENCE + TRIGGER -- ONLY needed if you chose PK strategy B above
--    (sequence-populated PK, adopt-in-place path). Skip this whole section if
--    you used the IDENTITY column strategy A.
--
--    CACHE 20 is Oracle's own default when CACHE is omitted -- a reasonable
--    general-purpose value trading a small amount of possible value loss on
--    instance restart for less dictionary contention under concurrent
--    NEXTVAL calls. NOORDER (the default) is preferred over ORDER except on
--    RAC deployments with a specific cross-instance strict-ordering
--    requirement (schema-model.md §7).
-- ----------------------------------------------------------------------------
-- DECLARE
--    l_count PLS_INTEGER;
-- BEGIN
--    SELECT COUNT(*) INTO l_count FROM user_sequences WHERE sequence_name = 'APP_ORDER_SEQ';
--    IF l_count = 0 THEN
--       EXECUTE IMMEDIATE '
--          CREATE SEQUENCE app_order_seq START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20';
--    END IF;
-- END;
-- /
--
-- CREATE OR REPLACE TRIGGER app_order_biu_trg
-- BEFORE INSERT OR UPDATE ON app_order_t
-- FOR EACH ROW
-- DECLARE
--    -- Swap this for whatever session/request-context mechanism the target
--    -- application actually populates (a SYS_CONTEXT namespace, a bind
--    -- parameter, a package-level session variable, ...).
--    l_user VARCHAR2(128 CHAR) := NVL(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'), USER);
-- BEGIN
--    IF INSERTING THEN
--       IF :NEW.order_id IS NULL THEN
--          :NEW.order_id := app_order_seq.NEXTVAL;
--       END IF;
--       :NEW.created_by            := NVL(:NEW.created_by, l_user);
--       :NEW.creation_date         := NVL(:NEW.creation_date, SYSTIMESTAMP);
--       :NEW.object_version_number := NVL(:NEW.object_version_number, 1);
--    END IF;
--
--    :NEW.last_updated_by  := l_user;
--    :NEW.last_update_date := SYSTIMESTAMP;
--
--    IF UPDATING THEN
--       :NEW.object_version_number := NVL(:OLD.object_version_number, 0) + 1;
--    END IF;
-- END;
-- /

-- ----------------------------------------------------------------------------
-- 5. SELF-REGISTRATION -- schema-model step 9 / schema-promote's
--    migration-versioning section. Manual step: add a row to the schema's
--    version/changelog table recording this migration's version id, this
--    script's name, and (if this change class needs one -- see
--    schema-promote's rollback-policy table) its paired rollback script name.
-- ----------------------------------------------------------------------------
