-- ============================================================================
-- schema-emit :: junction-table.sql
-- Illustrative worked example: APP_PRODUCT_CATEGORY_T -- many-to-many
-- association between APP_PRODUCT_T and APP_CATEGORY_T. Junction shape per
-- schema-model step 2: no data of its own beyond the two FKs (+ WHO/
-- ACTIVE_FLAG).
--
-- `APP_` is a PLACEHOLDER prefix -- substitute your project's actual
-- registered prefix and case convention (schema-model.md §0).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABLE -- identity-column PK strategy shown as the default (recommended
--    for greenfield, schema-model.md §7); the sequence+trigger alternative
--    is in business-table.sql section 4 -- apply the same substitution here
--    if this schema uses the adopt-in-place path instead.
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count
     FROM user_tables WHERE table_name = 'APP_PRODUCT_CATEGORY_T';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         CREATE TABLE app_product_category_t (
            product_category_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            product_id               NUMBER            NOT NULL,
            category_id              NUMBER            NOT NULL,
            active_flag               CHAR(1)          DEFAULT ''Y'' NOT NULL,
            created_by                VARCHAR2(128 CHAR)       NOT NULL,
            creation_date             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            last_updated_by           VARCHAR2(128 CHAR)       NOT NULL,
            last_update_date          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            object_version_number     NUMBER                   DEFAULT 1 NOT NULL,
            CONSTRAINT app_product_category_pk PRIMARY KEY (product_category_id),
            CONSTRAINT app_product_category_uk1 UNIQUE (product_id, category_id),
            CONSTRAINT app_product_category_ck1 CHECK (active_flag IN (''Y'',''N''))
         )';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 2. FK CONSTRAINTS -- ON DELETE rationale per schema-model step 3
--    (relationship-matrix rows):
--
--    | FK column   | Target             | ON DELETE           | Rationale                                    |
--    |-------------|--------------------| ---------------------|----------------------------------------------|
--    | product_id  | APP_PRODUCT_T      | CASCADE              | junction row has no meaning once the product |
--    |             |                    |                       | it categorizes is itself gone                |
--    | category_id | APP_CATEGORY_T     | RESTRICT (default)  | category is shared master data; must not     |
--    |             |                    |                       | silently disappear out from under a live     |
--    |             |                    |                       | product-category link                        |
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count
     FROM user_constraints
    WHERE table_name = 'APP_PRODUCT_CATEGORY_T' AND constraint_name = 'APP_PRODUCT_CATEGORY_FK1';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         ALTER TABLE app_product_category_t
            ADD CONSTRAINT app_product_category_fk1
            FOREIGN KEY (product_id) REFERENCES app_product_t (product_id)
            ON DELETE CASCADE';
   END IF;
END;
/

DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count
     FROM user_constraints
    WHERE table_name = 'APP_PRODUCT_CATEGORY_T' AND constraint_name = 'APP_PRODUCT_CATEGORY_FK2';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         ALTER TABLE app_product_category_t
            ADD CONSTRAINT app_product_category_fk2
            FOREIGN KEY (category_id) REFERENCES app_category_t (category_id)';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 3. FK INDEXES -- mandatory (schema-model.md §8: Oracle never auto-indexes
--    an FK column). product_id is already the leading column of
--    app_product_category_uk1, so it does not need a second index.
--    category_id is NOT the leading column of any existing index here, so
--    its FK index is required, not optional.
-- ----------------------------------------------------------------------------
DECLARE
   l_count PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'APP_PRODUCT_CATEGORY_IDX1';

   IF l_count = 0 THEN
      EXECUTE IMMEDIATE '
         CREATE INDEX app_product_category_idx1 ON app_product_category_t (category_id)';
   END IF;
END;
/

-- ----------------------------------------------------------------------------
-- 4. SELF-REGISTRATION -- schema-model step 9 / schema-promote's
--    migration-versioning section. Manual step: record this migration's
--    version id, forward script name, and paired rollback script name (if
--    this change class needs one) in the schema's version/changelog table.
-- ----------------------------------------------------------------------------
